### ISSUE TITLE
Argocd installation error

### ISSUE THREAD

**Issue by cbs-rschreijen** [erictummers/rancher-desktop-playground#6]
`kubectl apply -k . ` yields the following output (emphasis by me) when installing argocd using the instruction found here [argocd](https://github.com/cbs-rschreijen/rancher-desktop-playground/tree/main/argocd):

customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/applicationsets.argoproj.io created
customresourcedefinition.apiextensions.k8s.io/appprojects.argoproj.io created
clusterrole.rbac.authorization.k8s.io/argocd-application-controller created
clusterrole.rbac.authorization.k8s.io/argocd-server created
clusterrolebinding.rbac.authorization.k8s.io/argocd-application-controller created
clusterrolebinding.rbac.authorization.k8s.io/argocd-server created
Error from server (NotFound): error when creating ".": **namespaces "argocd" not found**
Error from server (NotFound): error when creating ".": namespaces "argocd" not found
Error from server (NotFound): error when creating ".": namespaces "argocd" not found
... etc.

**Comment by erictummers** [comment]
Solution is to create the namespace. Will update the readme.

**Comment by erictummers** [comment]
44e0bbc
